### PR TITLE
chore: upgrade std & rm makefile

### PR DESCRIPTION
**Pull request by satyarohith**
- upgrade std
- rm makefile

### CODE REVIEW

**Comment by kt3k** [comment]
Can we maybe remove `deno-old` CI? (or at least upgrade the `old` version number a little bit?)

**Comment by satyarohith** [comment]
> Can we maybe remove `deno-old` CI? (or at least upgrade the `old` version number a little bit?)

Let's remove it. @lucacasonato any objections?

**Comment by satyarohith** [comment]
> > Can we maybe remove `deno-old` CI? (or at least upgrade the `old` version number a little bit?)
> 
> Let's remove it. @lucacasonato any objections?

I didn't remove, but increased the old version requirement to `1.20.1`

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
