### PR TITLE
1.9.0

### PR DESCRIPTION
**Pull request by arnauorriols**

### CODE REVIEW

**Comment by arnauorriols** [comment]
> Make sure to push main to v1 branch when you release.

This has not been done since 1.4.0, and it does not make much sense tbh. Why do we need a version compat branch if main is still at that version?

**Comment by lucab** [comment]
@arnauorriols I think that may be for people using the github action as shown in the README:
```
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
```

(we don't have a `v1` tag in this repo, that ref is the one for the branch AFAIUI)

**Comment by satyarohith** [comment]
> > Make sure to push main to v1 branch when you release.
> 
> 
> 
> This has not been done since 1.4.0, and it does not make much sense tbh. Why do we need a version compat branch if main is still at that version? 

It's for GitHub action. Users use @v1 in their yml instead of specific version.

**Comment by arnauorriols** [comment]
Ah ok. Makes sense

**Pull request merged**
